name: dependent jobs

on: push

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: job1
#         run: echo "job1"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - name: job2
#         run: echo "job2"
#   job3:
#     runs-on: ubuntu-latest
#     needs: [job1, job2]
#     steps:
#       - name: job3
#         run: echo "job3"


# reversed dependencies
jobs:
  job1:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - name: job1
        run: echo "job1"
  job2:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: job2
        run: echo "job2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: job3
        run: echo "job3"